### ISSUE TITLE
It seems that a different -b path copies some files but not others

### ISSUE THREAD

**Issue by Jefffrey** [Nargonath/cra-build-watch#1]
I'm currently build-watching an application that has `manifest.json` and `favicon.ico` in `public/`. When I run `cra-build-watch -b someotherpath` then I find:

```
root/build/
    manifest.jsn
    favicon.ico
root/someotherpath
    index.html
    ...rest
```

Is this intended?

I've also tried to run: `cra-build-watch -b someotherpath -p someotherpath` but it doesn't seem to change anything.

**Comment by devxpy** [comment]
Like this ?

```
config.output.path = copyPublicFolder(buildPath ? handleBuildPath(buildPath) : paths.appBuild)

function copyPublicFolder(path) {
  if (!path) {
      path = paths.appBuild;
  }
  return fs.copy(paths.appPublic, path, {
    dereference: true,
    filter: file => file !== paths.appHtml,
  });
}
```

**Comment by Nargonath** [comment]
I was thinking more of something like that:
```js
const resolvedBuildPath = buildPath ? handleBuildPath(buildPath) : paths.appBuild;
config.output.path = resolvedBuildPath;

function copyPublicFolder() {
  return fs.copy(paths.appPublic, resolvedBuildPath, {
    dereference: true,
    filter: file => file !== paths.appHtml,
  });
}
```

The function `copyPublicFolder` is already not pure by relying on `paths.appHtml` and `paths.appPublic` from the context so let's just keep it that way for the buildPath.

**Comment by devxpy** [comment]
Sure, will issue a pull request. 
Can you advice me on how I can create a command so that I can do a dev build without a watcher?

_Why I need this:_
I want to be able to create a single build for each time django renders a template. 
A file watcher has to be started and maintained throughout the course of the django server's lifetime. On the other hand, we can just do a build each time django renders a template, since its development. This will also ensure any files that might have been missed by the file watcher.
