### ISSUE TITLE
Does not work after ejecting from create-react-app

### ISSUE THREAD

**Issue by burtontanner** [Nargonath/cra-build-watch#13]
Im really exited for this plugin. It is exactly what i have been looking for. I just need it to work after ejecting from create react app.

**Comment by Nargonath** [comment]
@burtontanner I haven't thought of it at first, but the thing is if CRA doesn't provide any support when you are ejecting that's because they cannot guarantee the changes you'll end up making to the config. The same logic applies for this tool. If you mess around with your webpack config I cannot guarantee that the tool will work and I have no way of knowing what every body will be doing with their config.

I don't think this tool should handle ejection. I directly modify CRA webpack config to make the development build on disk possible and if you touch your config you'll be messing around with what I did. The tool would not be able to work.

I'm closing this for now but I'm open to discussion.

**Comment by burtontanner** [comment]
@Nargonath that makes sense. I still need to find a solution to my problem and would like to leverage as much of your code as I can. I am probably going to fork your repo and fiddle around with it until I get it to work. My config files are untouched after ejecting. What do you think I would have to change to get it to work?

**Comment by Nargonath** [comment]
If you don't modify your config files, why are you ejecting in the first place?

**Comment by burtontanner** [comment]
@Nargonath I have just modified the jest configuration for testing. I doubt that your module will be affected by this so I didn't mention it. Could you point me in the right direction?

**Comment by Nargonath** [comment]
Indeed, it shouldn't be affected by it. I'm wondering if I will not implement it in the end. That's a pity CRA isn't built the same as Vue CLI did where they give a way to update the webpack config without having to eject. I could support it but really blindly assuming you didn't touch your webpack config and if ever you did then that's on you afterwards.
