### ISSUE TITLE
Can I use it with rescripts ?

### ISSUE THREAD

**Issue by joaovbibiano** [Nargonath/cra-build-watch#222]
I need to use rescripts to overried some configuration from CRA...  in this case to allow use namespaces on CRA.

Cra build watch, try run 

  "start": "react-scripts start",

but my script is
  "start": "rescripts start",

Thank you

**Comment by Nargonath** [comment]
`cra-build-watch` is meant to be used instead of the `react-scripts` binary. It monkey patches the `create-react-app` webpack configuration to allow for on-disk development build. 

I've never used `rescripts` but looking at their documentation it seems that they are meant to replace the `react-scripts` calls too so my guess is that these 2 tools don't work together. `cra-build-watch` would not be "aware" of all the changes made through `rescripts`.
