### ISSUE TITLE
How to utilize output to incorporate React application into an existing application?

### ISSUE THREAD

**Issue by cjones26** [Nargonath/cra-build-watch#26]
Hi @Nargonath, first of all, thanks for the great work!

Secondly, I see in the main page that you state this project can be utilized for:

> Incorporating your React application into an existing application.

This is exactly what I am attempting to do -- I have an Angular application which is currently integrated with React and I'm trying to figure out a way to utilize our existing React codebase directly from within this Angular project.

Being the build toolchain for the React app is far removed from Angular (and I really don't feel like replicating the entire configuration into our Angular app) -- I figured it may be possible to create a debug build of the React application, essentially pre-building it into a state where I might be able to do something like:

> const ComponentFromReact = require('main.chunk').ComponentFromReact

Due to my inexperience with webpack, I had hoped it would be this easy, though clearly it is not.  Is my intention an unreasonable pipe dream, or do you have any suggestions on how it may be accomplished?

Thanks!

-CJ

**Comment by Nargonath** [comment]
Hello @cjones26, thanks I'm glad you like it.

> Incorporating your React application into an existing application

What I meant by that is that some people have their frontend in other languages (C#, PHP, and so on) and cannot run their React App using the normal `react-scripts start` because the React App is just a subpart of their main app. So they need files to be served as part of their main app which was not possible without this package because by default `webpackDevServer` serves your files from memory and not disk.

Alas I'm not sure you can do what you are trying to achieve. I feel it is very unlikely to work because how would you use such component? 

1. You couldn't use JSX in your Angular application without changing your build chain to handle JSX. 
2. For such import to work, you'd need to export your components from the top level module of your React app.
3. Angular would not have any clue of what's going on in React land so I doubt they could collaborate.

What I know can work, is delegating a part of your Angular app to React but Angular would have to stay out of it. You would need to change the React mount point (it can be any DOM element). This use case is best suited for independent features that don't need to communicate with the main Angular app. I've never done it myself but I've talked to people who did. However if you want Angular to communicate with React I think prepare yourself to have a bad time and it is most likely going to be hard to maintain. If you really want to go that route, you could use DOM elements to share information (hidden elements and such with `data-` attributes) between the two app but you would need to check these elements on a regular basis which could hinder your performance as well.

Good luck!

**Comment by cjones26** [comment]
Got it -- thank for you the quick and detailed response!  I figured it was a long-shot, but worth giving it a try.

**Comment by Nargonath** [comment]
You're welcome
