### ISSUE TITLE
creating development build without watch

### ISSUE THREAD

**Issue by mecirmartin** [Nargonath/cra-build-watch#351]
Hey! I just want to create development build without running webpack watch.
I want to be able to create development build of CRA once and then deploy it on Vercel/Netlify.
 Is there any easy way to do this?

**Comment by mecirmartin** [comment]
I've looked into source code, and i could simply call `webpackCompiler.run()` instead of `webpackCompiler.watch()`
I know, that this package is called `cra-build-watch`, but do you think that it would be beneficial to add command just to generate single development build instead of watching?

Thanks for your work, this project was really helpful!

**Comment by Nargonath** [comment]
Hey @mecirmartin . Thank you for the kind words. I'm glad it was helpful to you. To be honest I haven't given much love to this project lately since I had other fish to fry. Also I initially intended this project to be temporary as I expected the PR mentioned in the README to be merged alas this has not been the case.

In the meantime `webpackDevServer` added a new option `writeOnDisk`. I've been playing with it on the beta branch. This would keep pretty much all of the CRA webpack config intact while also writing bundles on disk. This is for now quite a rough version. I removed all the features. I'm not sure yet what I'll be able to bring back  You can find more information here: https://github.com/Nargonath/cra-build-watch/releases/tag/v4.0.0-beta.1 and in the beta branch README: https://github.com/Nargonath/cra-build-watch/blob/beta/README.md#notes-for-version-v400-beta-testers. Would you mind give it a shot and tell me how it went for your use case, please?

**Comment by mecirmartin** [comment]
Sorry for late reply.
I tried the beta version of your tool, it works fine, basically it writes sources on disk when in development mode
However this does not suit my use case. I simply need to create build of CRA with react in development mode. This is not possible with `react-scripts` since the `NODE_ENV` is hardcoded to `production` whenever you call `react-scripts build`
I'm creating this development build to be deployed on web with react specifically in development mode, since in production mode react strips information about source of JSX elements which is crucial for application i'm working on 

The solution with using `webpackCompiler.run()` instead of `webpackCompiler.watch()` works fine, however i get this error when serving the bundle 
<img width="608" alt="Screenshot 2021-07-06 at 10 08 00" src="https://user-images.githubusercontent.com/55835379/124565191-0e0ef080-de42-11eb-85ff-1670157ef184.png">

I'll play around with webpack config and i'll try to fix this issue

**Comment by Nargonath** [comment]
@mecirmartin don't worry. I think the `writeOnDisk` option used in the `beta` version works also when you run `react-scripts start`. You should get a development build written on your file system. Have you already tried it?

**Comment by mecirmartin** [comment]
I think it could be done. Here is page deployed with modified `cra-build-watch`: https://inspiring-wing-c683b2.netlify.app/app/dashboard
React is in development mode
The problem is the error in console. Also after refresh it returns 404 on JS chunks, i have to manually remove the `app/dashboard` to get it to work again
I tried calling `compiler.close()` after `compiler.run()` in my fork of `cra-build-watch` but the function is undefined

I'll continue to play with this and i'll let you know

**Comment by Nargonath** [comment]
Sorry I don't have time to maintain this project anymore so I'll archive it and add a note in the README. Feel free to fork it as you see fit.
